### ISSUE TITLE
provide links to sources

### ISSUE THREAD

**Issue by mikapfl** [openclimatedata/globalwarmingpotentials#1]
Hi,

I think it would be quite valuable to provide links to sources for the values somehow. Sure, I can also google it, but if there's a link, it will save me some time trying to track down the right pdf. I'm not quite sure where that could be included, my ideas would be:
* in the datapackage.json under the `fields` entries.
* as a comment in the CSV

Cheers,

Mika

**Comment by rgieseke** [comment]
I agree, `sources` in the data package are no problem, as for the CSV files, i've been using something like 

```
# CSV Comment
# another comment
col1, col2
1,2
```

recently, which can also be set as a data package `comment` property. Only drawback is that this breaks GitHub rendering.

**Comment by rgieseke** [comment]
I got rid of the Data Package metadata (it's too messy, every time i look something up in the spec it has changed again ...) and added some links as comments in the CSV (they always float around somehow and then one can't find the origin).

I'll close this, feel free to re-open or PR with other suggestions :-)
