### ISSUE TITLE
Add GWP20 values

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/globalwarmingpotentials#10]

**Comment by chrisroadmap** [comment]
I was just browsing this repo as the proofs have come in for the Ch7 supplementary material. Could this issue be closed?

**Comment by danielhuppmann** [comment]
I don't have permission to close an issue here, but yes, I think it can be closed - and thanks for your reminder, I started a PR to get the new GWP metrics in our **iam-units** package (https://github.com/IAMconsortium/units/pull/38).
