### ISSUE TITLE
Put on conda forge

### ISSUE THREAD

**Issue by znicholls** [openclimatedata/globalwarmingpotentials#17]
Now that globalwarmingpotentials is a dependency of openscm-units, can we add globalwarmingpotentials to conda forge to ensure that our stack continues to be installable with conda please @rgieseke ?

**Comment by rgieseke** [comment]
Sounds like a good idea, PRs welcome!

**Comment by mikapfl** [comment]
https://github.com/conda-forge/staged-recipes/pull/17259

Maybe you can look at the recipe if anything looks wrong or should be changed. If everything looks fine, I'll ping the relevant conda team for their review.

**Comment by rgieseke** [comment]
Awesome, thank you! Looks good to me :+1:

**Comment by mikapfl** [comment]
https://anaconda.org/conda-forge/globalwarmingpotentials

**Comment by mikapfl** [comment]
I think this is solved.

**Comment by rgieseke** [comment]
Almost ;-) https://github.com/openclimatedata/globalwarmingpotentials/commit/c93f9f11120900e57de9e27f05d2f52df075f86b

Thanks again! (Does this update automatically from PyPI? There has been a 0.9.1 bugfix which contained the actual changes.)

**Comment by mikapfl** [comment]
yeah, there is an autoupdate-thing (have to approve the automatically done PR), but maybe it got confused because I approved 0.9.0 while 0.9.1 was also available. I'll see if it fixes automatically or I have to re-start the magic again.

**Comment by rgieseke** [comment]
Alright! :rocket:

**Comment by znicholls** [comment]
Legend thanks!
