### ISSUE TITLE
Handling of < values of GWPs

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/globalwarmingpotentials#8]
Some values are only given as `< 1` or `< 2500`

In some cases these have been added as `1`.
See e.g. https://github.com/openscm/openscm-units/pull/23#discussion_r609429037

One option might be to leave them out generally or list this somehow in the Readme.

**Comment by danielhuppmann** [comment]
Interesting point, hadn't realized this... Would be interesting to know if it is 1 in the sense of the ECB inflation rate target (below, but close to) or the Paris Agreement sense (well below)...

My preference would be to use NaN if no exact value can be given. When using that as input for **pint** and **iam_units** at least, this approach would result in an explicit error message if a user tried to convert that species.

**Comment by znicholls** [comment]
We used 1 as the upper-bound i.e. worst case. For these species, the CO2 equivalent is always so tiny that it's not worth worrying about (any decision is fine).
